/**
 * Express API Server
 * Project: user_application_20260213_093948
 * Auto-generated by AI Engineer Agent
 */

require('dotenv').config();
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
const rateLimit = require('express-rate-limit');

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(helmet());
app.use(cors());
app.use(morgan('combined'));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// Rate limiting
const limiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes
  max: 100, // Limit each IP to 100 requests per window
  message: { error: 'Too many requests, please try again later.' }
});
app.use('/api/', limiter);

// In-memory database (replace with real DB in production)
let items = [];
let users = [];
let itemIdCounter = 0;
let userIdCounter = 0;

// ============================================================================
// ROUTES
// ============================================================================

// Health check
app.get('/', (req, res) => {
  res.json({
    status: 'healthy',
    timestamp: new Date().toISOString(),
    version: '1.0.0'
  });
});

app.get('/health', (req, res) => {
  res.json({
    status: 'healthy',
    timestamp: new Date().toISOString(),
    version: '1.0.0',
    uptime: process.uptime()
  });
});

// Items CRUD
app.get('/api/items', (req, res) => {
  const { skip = 0, limit = 100 } = req.query;
  res.json(items.slice(Number(skip), Number(skip) + Number(limit)));
});

app.post('/api/items', (req, res) => {
  const { name, description, price, is_active = true } = req.body;

  if (!name || price === undefined) {
    return res.status(400).json({ error: 'Name and price are required' });
  }

  const newItem = {
    id: ++itemIdCounter,
    name,
    description,
    price: Number(price),
    is_active,
    created_at: new Date().toISOString()
  };

  items.push(newItem);
  res.status(201).json(newItem);
});

app.get('/api/items/:id', (req, res) => {
  const item = items.find(i => i.id === Number(req.params.id));
  if (!item) {
    return res.status(404).json({ error: 'Item not found' });
  }
  res.json(item);
});

app.delete('/api/items/:id', (req, res) => {
  const index = items.findIndex(i => i.id === Number(req.params.id));
  if (index === -1) {
    return res.status(404).json({ error: 'Item not found' });
  }
  items.splice(index, 1);
  res.status(204).send();
});

// Users
app.post('/api/users', (req, res) => {
  const { username, email, password } = req.body;

  if (!username || !email || !password) {
    return res.status(400).json({ error: 'Username, email, and password are required' });
  }

  const newUser = {
    id: ++userIdCounter,
    username,
    email,
    is_active: true,
    created_at: new Date().toISOString()
  };

  users.push({ ...newUser, password }); // Store password separately
  res.status(201).json(newUser);
});

app.get('/api/users', (req, res) => {
  // Don't return passwords
  res.json(users.map(({ password, ...user }) => user));
});

// Error handling middleware
app.use((err, req, res, next) => {
  console.error(err.stack);
  res.status(500).json({ error: 'Something went wrong!' });
});

// 404 handler
app.use((req, res) => {
  res.status(404).json({ error: 'Not found' });
});

// Start server
if (require.main === module) {
  app.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`);
    console.log(`API docs: http://localhost:${PORT}`);
  });
}

module.exports = app;
