"""
FastAPI Application - Auto-generated by AI Engineer
Project: user_application_20260213_093948
"""

import os
import logging
from datetime import datetime
from typing import Optional, List

from fastapi import FastAPI, HTTPException, Depends, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.security import OAuth2PasswordBearer, OAuth2PasswordRequestForm
from pydantic import BaseModel
import uvicorn

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Initialize FastAPI app
app = FastAPI(
    title="user_application_20260213_093948 API",
    description="Auto-generated API by AI Engineer Agent",
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc"
)

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Configure for production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# OAuth2 scheme
oauth2_scheme = OAuth2PasswordBearer(tokenUrl="token", auto_error=False)


# ============================================================================
# MODELS
# ============================================================================

class HealthResponse(BaseModel):
    status: str
    timestamp: str
    version: str


class ItemBase(BaseModel):
    name: str
    description: Optional[str] = None
    price: float
    is_active: bool = True


class ItemCreate(ItemBase):
    pass


class Item(ItemBase):
    id: int
    created_at: str

    class Config:
        from_attributes = True


class UserCreate(BaseModel):
    username: str
    email: str
    password: str


class User(BaseModel):
    id: int
    username: str
    email: str
    is_active: bool = True


class Token(BaseModel):
    access_token: str
    token_type: str


# ============================================================================
# IN-MEMORY DATABASE (Replace with real DB in production)
# ============================================================================

fake_db = {
    "users": [],
    "items": []
}

item_id_counter = 0
user_id_counter = 0


# ============================================================================
# ENDPOINTS
# ============================================================================

@app.get("/", response_model=HealthResponse)
async def root():
    """Health check endpoint"""
    return HealthResponse(
        status="healthy",
        timestamp=datetime.utcnow().isoformat(),
        version="1.0.0"
    )


@app.get("/health", response_model=HealthResponse)
async def health_check():
    """Detailed health check"""
    return HealthResponse(
        status="healthy",
        timestamp=datetime.utcnow().isoformat(),
        version="1.0.0"
    )


# Items CRUD
@app.get("/items", response_model=List[Item])
async def list_items(skip: int = 0, limit: int = 100):
    """List all items with pagination"""
    return fake_db["items"][skip:skip + limit]


@app.post("/items", response_model=Item, status_code=status.HTTP_201_CREATED)
async def create_item(item: ItemCreate):
    """Create a new item"""
    global item_id_counter
    item_id_counter += 1

    new_item = Item(
        id=item_id_counter,
        name=item.name,
        description=item.description,
        price=item.price,
        is_active=item.is_active,
        created_at=datetime.utcnow().isoformat()
    )
    fake_db["items"].append(new_item.model_dump())
    return new_item


@app.get("/items/{item_id}", response_model=Item)
async def get_item(item_id: int):
    """Get a specific item by ID"""
    for item in fake_db["items"]:
        if item["id"] == item_id:
            return Item(**item)
    raise HTTPException(status_code=404, detail="Item not found")


@app.delete("/items/{item_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_item(item_id: int):
    """Delete an item"""
    for i, item in enumerate(fake_db["items"]):
        if item["id"] == item_id:
            fake_db["items"].pop(i)
            return
    raise HTTPException(status_code=404, detail="Item not found")


# Users
@app.post("/users", response_model=User, status_code=status.HTTP_201_CREATED)
async def create_user(user: UserCreate):
    """Create a new user"""
    global user_id_counter
    user_id_counter += 1

    new_user = {
        "id": user_id_counter,
        "username": user.username,
        "email": user.email,
        "password": user.password,  # Hash in production!
        "is_active": True
    }
    fake_db["users"].append(new_user)
    return User(**new_user)


@app.get("/users", response_model=List[User])
async def list_users():
    """List all users"""
    return [User(**u) for u in fake_db["users"]]


# ============================================================================
# MAIN
# ============================================================================

if __name__ == "__main__":
    uvicorn.run(
        "main:app",
        host="0.0.0.0",
        port=int(os.getenv("PORT", 8000)),
        reload=True
    )
